### ISSUE TITLE
Materials

### ISSUE THREAD

**Issue by petrkucerak** [petrkucerak/budememachkovi#1]
[My-Invitation.pdf](https://github.com/petrkucerak/budememachkovi/files/8927118/My-Invitation.pdf)
[Svatební-web.docx](https://github.com/petrkucerak/budememachkovi/files/8927119/Svatebni-web.docx)
https://www.budeveselka.cz/adela-david-winterwedding
https://www.greetingsisland.com/terms

https://nextjsdev.com/lets-build-launch-countdown-timer-using-next-js-tailwind-css/

**Comment by kuda27** [comment]
![DL](https://user-images.githubusercontent.com/45317370/174455864-f4942e07-7e7d-451e-b46c-d3f8807e5c13.png)
![K](https://user-images.githubusercontent.com/45317370/174455870-969b899b-553f-4120-b612-d4cfe57c18d8.png)
![UL](https://user-images.githubusercontent.com/45317370/174455889-6c7595f2-1c63-4fd9-8e52-4ab8151f0afe.png)
![UR](https://user-images.githubusercontent.com/45317370/174455904-76266790-f1cc-42d6-9cc2-5c553ee32e8f.png)

**Comment by petrkucerak** [comment]
![kaja-1](https://user-images.githubusercontent.com/45851215/174645122-7cb928de-4357-43c4-ae6e-3384bc9dcbd2.jpg)
![kaja-2](https://user-images.githubusercontent.com/45851215/174645125-1e23a069-8957-4f5f-bcf4-3a9230402e8d.jpg)
![kaja-3](https://user-images.githubusercontent.com/45851215/174645128-a113a0ee-dff2-4f30-8bde-80117e4c7205.jpg)
![kaja-4](https://user-images.githubusercontent.com/45851215/174645133-51c97a15-e04c-4d1b-8fa6-559d35412461.jpg)
